### ISSUE TITLE
SEO URL does not work complete - each URL must be adjust separately

### ISSUE THREAD

**Issue by fczaja** [blooparksystems/website#24]
Impacted versions:
- 9.0
## Goal

Each time has a URL in the "SEO URL box" to change his and replace the old URL by 301.
Simultaneously, the URL of the English language version will be adapted by the new URL. The URLs of the languages German and English must be adjust separately.
### Current Behavior 1:

Once the URL has been altered in a successful product in the German language version, the English version of the page shows a 404 error.

Steps to Reproduce:

Go to Promote / Optimize SEO
Carrying in the product Airstream-2 a new URL
Then go to the English version
Here appears a 404 page
### Current Behavior 2:

Once the URL has been changed successfully in the "Service" in the German language version http://staging.supernova.bloopark.de/service can be seen in the German version of the new URL. In the English version is the old URL.

Steps to Reproduce:

Go to Promote / Optimize SEO
Carrying at the side of a new service URL
Then go to the English version
Here appears the old URL
### Expected Behavior:

When you insert a new URL into the "SEO URL field" must be overwritten by the new URL, the old URL. From the old URL 301 redirect is automatically set to the newly created URL.

This process must be repeated indefinitely.

The English URL must be adjust separately. If the English 'SEO URL field "a new URL inserted, it has priority over amendments to the German" SEO URL field ".

**Comment by kaerdsar** [comment]
According to this issue if you change the seo_url for a page in German via the Promote Panel, then the seo_url for the page in English must change too. But if we allow to translate seo_url  this is not supposed to change English seo_url when changes German seo_url. You have to edit the URL for each language unless it doesn't have value for other languages. If is correct this, The 'Current Behavior 2' is fine.

Please, tell me your idea about it.

**Comment by jholze** [comment]
@kaerdsar i think no, because the SEO urls are different for each language and they should be detached. If you change e.g. the name of a german Page like contact us or a basic cms page, it is not always necessary that the title for one of the other language should change too. 

One other thing from my side, you need to check how the suite works with more the 2 languages ;)

**Comment by fczaja** [comment]
Hi Cesar,

If a new URL in the "SEO URL Field" is entered in the German area, then the
English URL is changed. If a new URL will be inserted in the English
section ("SEO URL Field") then has the priority for the English area.

Freddy

2015-11-12 23:09 GMT+01:00 Cesar Lage <notifications@github.com>:

> According to this issue if you change the seo_url for a page in German via
> the Promote Panel, then the seo_url for the page in English must change
> too. But if we allow to translate seo_url this is not supposed to change
> English seo_url when changes German seo_url. You have to edit the URL for
> each language unless it doesn't have value for other languages. If is
> correct this, The 'Current Behavior 2' is fine.
>
> Please, tell me your idea about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blooparksystems/website/issues/24#issuecomment-156251758>
> .
>



-- 


Freddy Czaja
Leiter Online-Marketing SEO

E-Mail: fczaja@bloopark.de

bloopark systems GmbH & Co. KG
Bethovenstraße 4
39106 Magdeburg

Web: bloopark.de

**Comment by jholze** [comment]
Maybe we can implement the SEO fields for multiple languages like odoo did for the keywords. That we have in general a language switcher and all related fields changing based on the selected language. 

![odoo_9_promote_keyords](https://cloud.githubusercontent.com/assets/6851586/11141082/f2552c34-89e1-11e5-8dec-6afb58525d02.png)

**Comment by kaerdsar** [comment]
I created a pull request with a proposal about the image posted by @jholze. The idea is that we can edit SEO variables from the default language page for all languages. When you select a language all the fields reload to get the value for the language selected. 

Also I think we must change the Promote Panel interface in order to organize better the elements. Maybe we can put the language selector in the top of the window and then all the fields. But first, I would like we test if this variant works.

**Comment by rruebner** [comment]
@kaerdsar Hmm, if we use this proposal we should add an advice / hint that the values aren't saved when a user switch the language in the SEO promote panel part. Otherwise it will be irritating / frustrating for the user if he fills in all values for one language, switch to another language, fills in all values for this language, saves the changes and recognizes that only the last filled in values were saved for the default language at the end.

**Comment by rruebner** [comment]
@kaerdsar Furthermore the META description is not updated in the promote panel preview when I switch the language. Only after I filled in something in the META description the preview changed.

**Comment by rruebner** [comment]
@kaerdsar Please update the german hint text to: "Dieses Formular wird nur die Konfiguration für die ausgewählte Sprache speichern. Wenn Sie die Sprache wechseln, bevor Sie die SEO-Informationen speichern, gehen diese Daten verloren."
And change the german translations to the english ones in website_seo.pot.
